### ISSUE TITLE
ModuleNotFoundError: No module named 'safe_rl.utils'

### ISSUE THREAD

**Issue by suitangxiaoyi** [huawei-noah/HEBO#103]
Hi, I have installed the module safe_rl:
`(sauterl) D:\reinforcement learning\HEBO-master>pip install safe_rl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting safe_rl
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9f/44/2bb7205bba54df944da8a1472515595b016aa0318abb49399e59f3713d83/safe_rl-0.0.1-py3-none-any.whl (2.1 kB)
Installing collected packages: safe_rl
Successfully installed safe_rl-0.0.1`
But when I run
`python SIMMER\main.py --experiment 11 --num-exps 5`
 the result error is
![1733714465370](https://github.com/user-attachments/assets/5aab4ed4-ef24-4813-9db4-5885ea4ac982)
How can I solve this problem

**Comment by AntGro** [comment]
Hi, I would advise following [the installation guide](https://github.com/huawei-noah/HEBO/tree/master/SIMMER#installation).
