### ISSUE TITLE
asap7.lib not Found

### ISSUE THREAD

**Issue by Flians** [huawei-noah/HEBO#12]
Hello,
When I run the command:
`python ./core/algos/bo/boils/main_multi_boils.py --designs_group_id log2 --n_parallel $n_parallel 1 --seq_length 20 --mapping fpga --action_space_id extended --ref_abc_seq resyn2 --n_total_evals 200 --n_initial 20 --device 0 --lut_inputs 4 --use_yosys 1 --standardise --ard --acq ei --kernel_type ssk --length_init_discrete_factor .666 --failtol 40 --objective lut --seed 0`
It shows 'asap7.lib' not found. Can you share it?
Thank you.

**Comment by phyzhenli** [comment]
It's a technology library for Logic synthesis.

**Comment by caicaicaia** [comment]
I have met the problem too. How to address it?

**Comment by AntGro** [comment]
Hi, it seems that asap7.lib coming from DRILLS repo is no longer available online at this stage. I can only point to this other issue (solution is to send an email to one of DRILLS' contributors): https://github.com/scale-lab/DRiLLS/issues/10
