### ISSUE TITLE
CUDA out of memory for BOiLS

### ISSUE THREAD

**Issue by Flians** [huawei-noah/HEBO#13]
`X1_full = torch.repeat_interleave(X1.unsqueeze(0), len(indicies), dim=0)[
RuntimeError: CUDA out of memory. Tried to allocate 3.89 GiB (GPU 0; 11.93 GiB total capacity; 3.49 GiB already allocated; 3.65 GiB free; 7.67 GiB reserved in total by PyTorch)
`

BOiLS takes up too many GPU memories. Do you have any suggestions about it?

**Comment by AntGro** [comment]
Hi! This is indeed a drawback of the current SSK implementation. We are actually working on this aspect to make SSK computation less memory intensive. For the only direct fix would be to use GP with inducing points when the number of training points is too large for the exact GP to be fit on a GPU.
