### ISSUE TITLE
mixed_variable_operator was removed from pymoo.operators in v0.6.0. 

### ISSUE THREAD

**Issue by bouthilx** [huawei-noah/HEBO#19]
Since release v0.6.0 of pymoo yesterday (https://github.com/anyoptimization/pymoo/releases/tag/0.6.0), HEBO's acq_optimizers fail to import because of an ImportError during the module's own imports:

```
  tests/unittests/algo/long/hebo/test_hebo.py:9: in <module>
      from hebo.models.model_factory import model_dict
  .tox/algo/lib/python3.7/site-packages/hebo/__init__.py:10: in <module>
      from . import acq_optimizers
  .tox/algo/lib/python3.7/site-packages/hebo/acq_optimizers/__init__.py:10: in <module>
      from . import evolution_optimizer
  .tox/algo/lib/python3.7/site-packages/hebo/acq_optimizers/evolution_optimizer.py:15: in <module>
      from pymoo.operators.mixed_variable_operator import MixedVariableMutation, MixedVariableCrossover
```

**Comment by julioasotodv** [comment]
Indeed, `pymoo==0.6.0` causes import issues

**Comment by LXlearning** [comment]
the same problems with me

**Comment by gengjun** [comment]
same here, also pymoo 0.5.0 only support up to python 3.8, so for python 3.9 and 3.10, there's no way to use hebo

**Comment by gengjun** [comment]
I may have a fix here: https://github.com/huawei-noah/HEBO/pull/35

**Comment by bouthilx** [comment]
Latest numpy release does not contain `numpy.object` anymore, which is now causing even pymoo==0.5.0 to fail.
