### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Bouchenemehdi24** [huawei-noah/HEBO#26]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-66b51f58dfeb>](https://localhost:8080/#) in <module>
      8 
      9 
---> 10 from hebo.optimizers.hebo import HEBO
     11 from hebo.optimizers.bo import BO
     12 

2 frames
[/usr/local/lib/python3.7/dist-packages/hebo/acq_optimizers/evolution_optimizer.py](https://localhost:8080/#) in <module>
     13 from torch.quasirandom import SobolEngine
     14 from pymoo.factory import get_problem, get_mutation, get_crossover, get_algorithm
---> 15 from pymoo.operators.mixed_variable_operator import MixedVariableMutation, MixedVariableCrossover
     16 from pymoo.optimize import minimize
     17 from pymoo.core.problem import Problem

ModuleNotFoundError: No module named 'pymoo.operators.mixed_variable_operator'

**Comment by AntGro** [comment]
Hi Mohammed,
Thank you for raising this issue.
You can try to install pymoo version 0.5.0, that should fix your problem. I think you now have the latest version of pymoo installed (as in our requirements.txt we have pymoo>=0.5.0) and there are some changes in their API. We will handle this and update the repo.

Best,
Antoine

**Comment by Jet132** [comment]
Could you please release the fix on PyPI? Else everyone will first have to find this issue to use the library.

**Comment by fostiropoulos** [comment]
The issue persists.

**Comment by StephanAkkerman** [comment]
Can this please be fixed?

**Comment by StephanAkkerman** [comment]
The current evolution_optimizer.py implementation on GitHub seems to not use the deprecated functions, maybe updating the PyPI package will be sufficient as a fix?

**Comment by StephanAkkerman** [comment]
For anyone else having this problem: `pip install git+https://github.com/huawei-noah/HEBO.git#subdirectory=HEBO` fixes it
