### ISSUE TITLE
The inverse_transform does not work as expected.

### ISSUE THREAD

**Issue by kaimo455** [huawei-noah/HEBO#34]
Original Codes:
https://github.com/huawei-noah/HEBO/blob/f9b7f578bd703ba2f47840a581bb4294faff1e12/HEBO/hebo/design_space/int_exponent_param.py#L33-L34

As I understand here the function `inverse_transform()` should worked as **_taking a arbiraty input(s) as exponent_**, however we cannot guaranteed the input(s) as `Int` dtype. In such case, if we have codes as below:

https://github.com/huawei-noah/HEBO/blob/f9b7f578bd703ba2f47840a581bb4294faff1e12/HEBO/hebo/optimizers/evolution.py#L71-L83

Here `x` could be arbitary number, assuming we have `x=np.array([5.4])`, write some toy codes below to demostrate the problem:
```python
from hebo.design_space.int_exponent_param import IntExponentPara
p = IntExponentPara({'name': 'p', 'base': 2, 'lb': 32, 'ub': 256})  # expected parameter values [32, 64, 128, 256]
x = np.array([5.4])
print(p.inverse_transform(x))
# >>> [42]
# 2**5.4=42.22, after astype(int) is 42, but not in valid values [32, 64, 128, 256]
```

That is to say, what `optimzer.evolution.suggest()` produces suggested parameter(s) could violate its definition. To resovled this issue, I  open a pull request.
 #33

**Comment by AntGro** [comment]
Hi kaimo455,
Thanks for raising this issue. I will accept your pull request.
Best
