### ISSUE TITLE
multi-objective optimization

### ISSUE THREAD

**Issue by seefun** [huawei-noah/HEBO#4]
how to use HEBO to deal with multi-objective optimization？

**Comment by Alaya-in-Matrix** [comment]
Hi @seefun we now have limited support for multi-objective optimization in `hebo.optimizers.general`, which supports constrained multi-objective optimization,  details can be seen in the documentation. 

We are also planning to add more advanced multi-objective optimization algorithms.

**Comment by Alaya-in-Matrix** [comment]
@seefun the documentation about MOO can be seen here https://hebo.readthedocs.io/en/latest/mo_constrained.html
