### ISSUE TITLE
pymoo has no module 'algorithms.so_genetic_algorithm'

### ISSUE THREAD

**Issue by nathanwalker-sp** [huawei-noah/HEBO#5]
When running the example code for sklearn tuner, I get the following error message

`ModuleNotFoundError: No module named 'pymoo.algorithms.so_genetic_algorithm'`

The line of code in question is `from pymoo.algorithms.so_genetic_algorithm import GA` within `evolution_optimizer.py`

I can reproduce it standalone as well (i.e. installing pymoo and trying to run that import), and I don't see this algorithm in pymoo's API reference.

Looks like [this comes from a breaking change in pymoo 0.5.0](https://pymoo.org/versions.html#0.5.0), which they detailed "The package structure has been modified to distinguish between single- and multi-objective optimization more clearly."

Based on their [updated API for version 0.5.0](https://pymoo.org/api/algorithms.html), I *believe* but am not sure that the genetic algorithm import needs to be changed to:

`from pymoo.algorithms.soo.nonconvex.ga import GA`

**Comment by Alaya-in-Matrix** [comment]
We have updated the code to be compatible to newer `pymoo`

**Comment by gengjun** [comment]
it seems as of today, the package 0.3.2 on https://pypi.org/project/HEBO/ still have similar issues with pymoo, i still need to downgrade to 0.5.0 from 0.6.0 to make it work...
