### ISSUE TITLE
missing library_file asap7.lib

### ISSUE THREAD

**Issue by charliecaffe** [huawei-noah/HEBO#63]
We are reproducing the results of the work [HEBO/BOiLS at master](https://github.com/huawei-noah/HEBO/tree/master/BOiLS). An AssertionError about the missing of library_file asap7.lib is caught when running the following commands.
`python ./core/algos/bo/boils/main_multi_boils.py --designs_group_id log2 --n_parallel $n_parallel 1 \
                      --seq_length 20 --mapping fpga --action_space_id extended --ref_abc_seq resyn2 \
                      --n_total_evals 200 --n_initial 20 --device 0 --lut_inputs 4 --use_yosys 1  \
                      --standardise --ard --acq ei --kernel_type ssk \
                      --length_init_discrete_factor .666 --failtol 40 \
                      --objective both \
                      --seed 0`
Could you please provide it? Thanks.

**Comment by AntGro** [comment]
https://github.com/huawei-noah/HEBO/issues/12#issuecomment-1788799527
