### ISSUE TITLE
期待AIRBO的更新

### ISSUE THREAD

**Issue by zoubaikongyu** [huawei-noah/HEBO#69]
首先非常感谢研究人员的开源工作！
我在近期的文献阅读中发现了“Efficient Robust Bayesian Optimization for Arbitrary Uncertain Inputs”这篇由您撰写的文章，这篇文章我认为非常优秀。在学习过程中，我注意到文章标注了其将开源于HEBO项目，不过可能受限于时间问题，目前该部分尚未更新。
非常期待该部分的后续更新！
同时祝各位新年快乐！

**Comment by yanglin-jason** [comment]
Thanks for your attention. It has taken us some time to clear up the code but now it is done :) You can find the corresponding code in the AIRBO directory.
