### ISSUE TITLE
An unexpected bug

### ISSUE THREAD

**Issue by KNwbq** [huawei-noah/HEBO#7]
When I using hebo.sklearn_tuner to optimize the hyperparameters of xgboost, there is  an error that "TypeError: 'float' object cannot be interpreted as an integer", so I made a breakpoint to enter the function to find out the reason. It's because the dataframe class method iloc will transform the data type from int to float, which will cause the error.

**Comment by Alaya-in-Matrix** [comment]
I've just made a bugfix commit that forces integer parameters being integer, however I've not push that commit to pypi, so you may need to install from source by `pip install -e .`

**Comment by KNwbq** [comment]
Got it. Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wenlong ***@***.***&gt;; 
发送时间: 2022年1月5日(星期三) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/HEBO] An unexpected bug (Issue #7)





 
I've just made a bugfix commit that forces integer parameters being integer, however I've not push that commit to pypi, so you may need to install from source by pip install -e .
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
