### ISSUE TITLE
Typo in hebo/optimizers/hebo.py: Incorrect Parameter axsi instead of axis

### ISSUE THREAD

**Issue by taufiqulf** [huawei-noah/HEBO#72]
### Description ###

There is a typo in the `hebo/optimizers/hebo.py` file on line 172 where the parameter `axsi` is used instead of `axis`.

### Location ###

File : `hebo/optimizers/hebo.py`
Line : 172

### Current Code ###

```
if rec.shape[0] < n_suggestions:
    rand_rec = self.quasi_sample(n_suggestions - rec.shape[0], fix_input)
    rec = pd.concat([rec, rand_rec], axsi=0, ignore_index=True)
```

### Issue ###

The parameter should be `axis`, not `axsi`.

### Suggested Fix ###

Replace `axsi` with `axis`:
```
if rec.shape[0] < n_suggestions:
    rand_rec = self.quasi_sample(n_suggestions - rec.shape[0], fix_input)
    rec = pd.concat([rec, rand_rec], axis=0, ignore_index=True)
```

### Impact ###

This typo may cause runtime errors when this code path is executed, as `pd.concat` does not recognize `axsi` as a valid parameter.

**Comment by AntGro** [comment]
Thanks for pointing this out.
