### ISSUE TITLE
Superfluous LightGBM Dependency Apple Silicon Incompatible

### ISSUE THREAD

**Issue by bbstats** [huawei-noah/HEBO#74]
This package requires `lightgbm` - which I can find no instance of being used in the code - however, this breaks the install on Apple silicon, e.g. there are no simple ways to install LightGBM on Mac M1/M2/M3.

If this unneeded dependency can be removed, I can simply `pip install HEBO` in my code once more!

**Comment by bbstats** [comment]
While lightgbm now supports apple silicon - this is still probably worth investigating, can we just remove the lightgbm dependency?

**Comment by AntGro** [comment]
It is now removed in our latest release.
