### ISSUE TITLE
ValueError in HEBO

### ISSUE THREAD

**Issue by qlchen2** [huawei-noah/HEBO#75]
HEBO/hebo/models/gp/gp.py: Line 154
`pred = torch.distributions.normal.Normal(torch.zeros(len(Xc)), torch.eye(len(Xc)))
`
should be written as,
`pred = torch.distributions.MultivariateNormal(torch.zeros(len(Xc)), torch.eye(len(Xc))).sample()`

**Comment by AntGro** [comment]
That's right, except that I don't think we need the `.sample()`. 
https://github.com/huawei-noah/HEBO/commit/b60f41aa862b4c5148e31ab4981890da6d41f2b1

**Comment by qlchen2** [comment]
Exactly. @AntGro
