### ISSUE TITLE
mcbo test_aig_task.py error

### ISSUE THREAD

**Issue by gongyuzhangzhao** [huawei-noah/HEBO#78]
When I try to run the test_aig_task.py file inside the test folder of mcbo, I first encountered a group error. I looked up the corresponding groups and selected one, naming the designs_group_id in task_kwargs as 'open_abc_orig'. Are there any other options or alternative solutions for this?

Secondly, when I ran it again, I encountered a TypeError: __init__() missing 3 required positional arguments: 'obj_dims', 'out_constr_dims', and 'out_upper_constr_vals'. Currently, I'm trying to solve this by providing values for these three arguments. Is this a reasonable solution? If so, how do I know what values are most appropriate to assign?

Lastly, I encountered a PermissionError: [Errno 13] Permission denied: '/root/autodl-tmp/MCBO2/abc'. What should be the path filled in abc_release_path.txt?

**Comment by gongyuzhangzhao** [comment]
I have tried changing the path in abc_release_path.txt to /root/autodl-tmp/MCBO2/libs/EDA/abc, but I still encountered the same PermissionError.

**Comment by AntGro** [comment]
Can you try to do in a terminal `chmod u+x /root/autodl-tmp/MCBO2/libs/EDA/abc` to change the permission?

**Comment by AntGro** [comment]
> When I try to run the test_aig_task.py file inside the test folder of mcbo, I first encountered a group error. I looked up the corresponding groups and selected one, naming the designs_group_id in task_kwargs as 'open_abc_orig'. Are there any other options or alternative solutions for this? 

You can see the options for the choice of `designs_group_id` as the keys of the dictionary `DESIGN_GROUPS` in [mcbo/tasks/eda_seq_opt/utils/utils_design_groups.py](https://github.com/huawei-noah/HEBO/blob/b60f41aa862b4c5148e31ab4981890da6d41f2b1/MCBO/mcbo/tasks/eda_seq_opt/utils/utils_design_groups.py#L40), and you can add manually new groups there if you want to run on another set of circuits.

**Comment by gongyuzhangzhao** [comment]
ohh！Thank you very much for your help. I have solved the previous issue, but now I'm facing a challenge related to a previous question about aig_optimization, which is the missing libreadline.so.7. However, when I try to install it using sudo apt install libreadline7, I encounter the error: "E: Package 'libreadline7' has no installation candidate." I have searched for solutions online but haven't found the right one yet. If you have any suggestions, please let me know.

**Comment by gongyuzhangzhao** [comment]
I tried creating a symbolic link using ln -s libreadline.so.8 libreadline.so.7 but it didn't work.
