### ISSUE TITLE
Wrong links to ROS-LLM in paper

### ISSUE THREAD

**Issue by CumulusAlpha** [huawei-noah/HEBO#94]
In your paper _ROS-LLM: A ROS framework for embodied AI with task feedback and structured reasoning_, the link to your code is unable to access, what happened? I just found the link you showed on the paper is _https://github.com/huawei-noah/HEBO/tree/master/ROSLLM_, however, the right one is _https://github.com/huawei-noah/HEBO/tree/rosllm/ROSLLM_

**Comment by manxunyu** [comment]
Hello, have you successfully used this code(https://github.com/huawei-noah/HEBO/tree/rosllm/ROSLLM)?

**Comment by CumulusAlpha** [comment]
tks a lot
